#!/bin/sh
#-*- sh -*-

case $1 in
        play)
                ../../tophat main src/main.um
        ;;
        check)
                ../../tophat check main src/main.um
                
                for d in test/*; do
                        TEST_PFX="%d/" ../../tophat check main "$d/main.um"
                done
        ;;
        test)
                if [ -z "$2" ]; then
                        echo -e "Specify the test. \n$0 $1 test_name" 
                        exit 1
                elif [[ -d "test/$2" && -f "test/$2/main.um" ]]; then 
                        TEST_PFX="test/$2/" ../../tophat main "test/$2/main.um"
                else
                        echo "No test \"$2\"." 
                        exit 2
                fi
        ;;
        *)
                echo "Use commands: test, check, play"
                exit 3
        ;;
esac
