#!/bin/sh
case $1 in
        play)
                ../../tophat root tophat.dat
        ;;
        check)
                ../../tophat check root tophat.dat
                
                for d in test/*; do
                        TEST_PFX="%d/" ../../tophat check root "$d"
                done
        ;;
        test)
                if [ -z "$2" ]; then
                        echo -e "Specify the test. \n$0 $1 test_name" 
                        exit 1
                elif [[ -d "test/$2" ]]; then 
                        TEST_PFX="test/$2/" ../../tophat root "test/$2"
                else
                        echo "No test \"$2\"." 
                        exit 2
                fi
        ;;
        *)
                echo "Use commands: test, check, play"
                exit 3
        ;;
esac
